version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - laravel_network

  webserver:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
    - .:/var/www
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_network

  db:
      image: mysql:5.7
      container_name: laravel_db
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: laravel
      ports:
        - "3306:3306"
      volumes:
        - mysql_data:/var/lib/mysql  
      networks:
        - laravel_network


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: laravel_db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 4096M 
    ports:
      - "8081:80"
    networks:
      - laravel_network


networks:
  laravel_network:

volumes:
  mysql_data:
